import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();


  return (
    <>
      <Head>
        <title>Witter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/social.png" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">


        

        <div className="border-slate-400 p-4"> 
        {!user.isSignedIn && <SignInButton />}
        {!!user.isSignedIn && <SignOutButton />}
        </div>
       
       <div>
       {data?.map((post) => (
        <div key={post.id}>{post.content}</div>
       ))}

       </div>
        </div>
      </main>
    </>
  );
}
